version: '3'

services:

  web:
    container_name: docker-web-stack
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./web:/home/web
    ports:
      - 5000-5050:5000-5050

  redis:
    image: redis:alpine3.17
    restart: always
    volumes:
      - ./data/redis:/data

  memcached:
    image: memcached:alpine3.17
    restart: always

  mariadb:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql

  postgres:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}"
      - "ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
